# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 129)
        Form.setMinimumSize(QtCore.QSize(300, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_name = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout.addWidget(self.label_name)
        self.label_discount = QtWidgets.QLabel(parent=Form)
        self.label_discount.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_discount.setFont(font)
        self.label_discount.setObjectName("label_discount")
        self.horizontalLayout.addWidget(self.label_discount)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_director = QtWidgets.QLabel(parent=Form)
        self.label_director.setMinimumSize(QtCore.QSize(0, 15))
        self.label_director.setObjectName("label_director")
        self.verticalLayout.addWidget(self.label_director)
        self.label_phone = QtWidgets.QLabel(parent=Form)
        self.label_phone.setMinimumSize(QtCore.QSize(0, 15))
        self.label_phone.setObjectName("label_phone")
        self.verticalLayout.addWidget(self.label_phone)
        self.label_rating = QtWidgets.QLabel(parent=Form)
        self.label_rating.setMinimumSize(QtCore.QSize(0, 15))
        self.label_rating.setObjectName("label_rating")
        self.verticalLayout.addWidget(self.label_rating)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_name.setText(_translate("Form", "TextLabel"))
        self.label_discount.setText(_translate("Form", "TextLabel"))
        self.label_director.setText(_translate("Form", "TextLabel"))
        self.label_phone.setText(_translate("Form", "TextLabel"))
        self.label_rating.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
