services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - ./pgdata:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
